STOP SLAVE;
RESET MASTER;


CHANGE MASTER TO
  MASTER_HOST='mariadb1',
  MASTER_USER='root',
  MASTER_PASSWORD='password',
  MASTER_PORT=3306,
  MASTER_CONNECT_RETRY=10,
  MASTER_USE_GTID = slave_pos;

START SLAVE;
